server.port=8082

spring.datasource.url=jdbc:h2:mem:orderdb

product.service.url=http://product-service:8080/api/products
unleash.api-url=http://unleash-server:4242/api
unleash.api-token=${UNLEASH_API_TOKEN:*:*.default-token}