server.port=8080

spring.datasource.url=jdbc:h2:mem:productdb
spring.jpa.hibernate.ddl-auto=update

unleash.api-url=http://unleash-server:4242/api
unleash.api-token=${UNLEASH_API_TOKEN:*:*.default-token}